import { J } from '@Jeact';
import './post.sass';
import Broken from '../broken.jpg';
import Img from './20120509.jpg';

export default function Post(prop){
  const title = `Forgotten Events`;
  document.title = title;
  return (
    <section className='post'>
      <h1>{title}</h1>
      <div className='post-content'>
        <article>
          <section>
            <h2>Forgotten Events</h2>
            <p>I just returned to Hong Kong from Shanghai and the work over the past few days has been nonstop. I look back upon the two days before leaving for Shanghai, and they were extremely hectic too. I had to record in the studio as well as visit the elderly homes, so I forgot to tell everyone something that happened. On June 9, Kim Hee came to Hong Kong to record two songs with me. The two songs are going to be performed at the charity concert scheduled to take place in September. Since both Kim Hee and myself are too busy, it took a lot of organization in our schedules to arrange the time for the two of us to get together and record the tracks. When Kim Hee and her manager arrived in Hong Kong, I of course did my best to play a good host and took them to dinner and then to karaoke to practice, and took them back to their hotels to rest.
            </p><p>The next day, when Kim Hee recorded the song at the studio her performance shocked the producer. She sang, Understand My Heart and Everyday in My Life and her Mandarin pronunciation was extremely accurate. I believed that she worked very hard on it since I gave her the CD with the songs. Please keep in mind that Kim Hee does not know Chinese, so she has to memorize the pronunciation of every word, as well as the rhythm and tune of the song. Ironically enough, she remembered how to pronounce and sing the song from beginning to end and I forgot the lyrics and couldn't keep up with the rhythm! How embarrassing!
            </p><p>After recording the two tracks, I discovered that it would be Kim Hee's birthday the next day. She would be returning to Korea the next day, so Mr. Yeung (my good friend and business partner Mr. Albert Yeung) and I decided to organize a surprise birthday party for her. Due to a lack of preparation time, it wasn't a big surprise party; just having karaoke with some friends and colleagues. To be honest, I wasn't in a good mood that night, and as I watched everyone drinking and singing their hearts out, I was thinking about a lot of things, like the work I have to do in Shanghai and some business problems I have. As I kept thinking about things, I listened to the girls at the party screaming and drinking, and I began to get irritated by it all. I told the female colleagues from the company to leave first, and the party ended soon after.
            </p>
          </section>
          <section>
            <h2>Shanghai International Film Festival</h2>
            <p>On June 11, Kim Hee and company returned to Korea, and I had work of my own to complete. I flew to Shanghai in the morning to attend the 8th Shanghai International Film Festival. The festival opened at the Shanghai Grand Theater, and to create the celebratory mood of 100 Years of Chinese Cinema, the Film Festival Committee specifically rolled out the red carpet, used money to book a flight and flew 300 celebrities from Beijing to Shanghai. When I arrived at the event, I saw many passionate fans screaming and waving, and the huge, wild crowd of fans made the already exciting event even more so!
            </p><p>After I arrived at the film festival, I found out that the organizers presented special awards to director Zhang Yimou and myself: the Outstanding Contribution to Chinese Films Award. To be honest, when I went on stage I was shocked that they presented the award to me. I was only meant to attend the festival as a guest and a panel speaker; I never expected to receive this surprise award.
            </p><p>On stage I said to everyone that to begin with, I wouldn't dare say that I have contributed much. If I really have made any contributions, I have to thank people who worked in the past and people who helped us along the way. I want to learn from people in the past, and I could leave my mark upon the marks they have already made, so that the younger generation can find the path easier to follow and to progress further. Secondly, to receive this award with director Zhang Yimou is a big personal honor for me.
              </p><p>I should also let you know that this Outstanding Contribution Award Cup is very heavy, and is made by Yeung Wai San's glass factory. I am not kidding you, it is so very, very heavy, and I was beating my brain trying to figure out a way to handle the cup. If I put it in a box and ship it back to Hong Kong, it might be damaged along the way, but it was too heavy to take it on the plane as hand-carry luggage. In the end I decided the safest way was to give it to my furniture factory in Shanghai to deliver along with their next cargo to Hong Kong.
              </p>
            </section>
          <section>
            <h2>The 8th Shanghai International Film Festival Jin Jue International Film Forum</h2>
            <p>The next day I attended a film forum that was the main forum at the 8th Shanghai International Film Festival. It was a forum discussing how to further develop the martial arts film genre. They called it Chinese Martial Arts Films Influence to the World. I couldn't believe that a small film forum caused some minor chaos. It was because this forum attracted a lot of experts and the media's attention and when I arrived the scene got rather chaotic. There were reporters who were stuck in the lift for a few minutes before they could get away, that really went beyond my expectations.
            </p><p>To be honest, when I got on stage, there was thunderous applause, and for someone as experienced as myself at dealing with big scenes like this, I got pretty nervous. I was nervous because the topic of Chinese Martial Arts Cinema is huge, I wasn't sure that I could express myself accurately. I wasn't even quite sure how to begin! However, I do think I am the most qualified to make comments on martial arts films. I started shooting martial arts films when I was 6 1/2 years old. At that time, they used the Huang Fei Hong series to express Chinese martial arts, and they were known as Palm Kung-Fu Films. The actors fought very slowly; when four people were fighting, two people were behind them, waiting to fight. To the era of Wang Yu, it evolved to where the protagonist would make a turn and forty to fifty baddies would be dead. It wasn't until the Bruce Lee era that martial arts films had the required dynamics. At the time I was influenced by Bruce Lee films and returned to study martial arts in a school. Thus began the Jackie Chan Era.
            </p><p>When they discussed my biggest contribution to martial arts films, I guess it would be adding humor to martial arts, and making people feel happy as they watched a martial arts film. Later I felt that my films could enter the international arena, so that audience members around the world could love Chinese martial arts films. At the moment, I have many fans in the UK, Australia, Canada, Africa, Korea, and Japan, and I have fan clubs all around the world. After watching my martial arts films some of my fans started to study Chinese and they went to China to study martial arts. When they come and see me in Hong Kong, many would come and listen to me speak in Mandarin. Many Germans can even sing Understand My Heart. That is the influence I have upon them. It's similar to the recent Korean Trend - many extremely popular Korean Films are imported into China and have started to influence its audience. Now, many Chinese are opening Korean restaurants, going on holidays in Korea - and I have many friends who are studying Korean.
            </p><p>In my opinion, as long as the films are well made, and can be accepted by the international audience, that would be our influence. Due to the success of Hong Kong martial arts films, they have become a genre, and directors such as Zhang Yimou and Ang Lee's achievements are significant. They further developed the aesthetics of traditional martial arts films, making them much more beautiful, and the quality of these films can match major Hollywood productions.
            </p><p>I have been famous in Hollywood for many years, and I understand the acceptance and significance of martial arts films in the international arena. I think that to promote Chinese actors and Chinese traditional culture to the international audiences, martial arts films would be the ideal medium. I hope that there will be more foreigners studying Chinese in the future and developing more interest in our culture. I have two Australian students who went to study Chinese in Beijing, and under my influence, they started wearing Chinese clothing. I told them that to study from me, the first thing they need is to learn to be a Chinese. I hope that Chinese filmmakers can use every opportunity they have and bring their own culture along with them, which could let more foreigners appreciate and like Chinese culture, then they would start to learn the language and develop a further understanding of Chinese culture.
            </p><p>I also think that the biggest advantage of martial arts films is that it is easy to understand and is not really burdened by the language barrier. When you watch Zhang Yimou's Raise the Red Lantern, he had to work so hard to think up the dialogue "Which mistresses' room to head to tonight?" But the most brilliant dialogue might become a YES or NO when translated into English, and it makes it extremely difficult for a Western audience to understand the deeper meanings of the film. But with action films it is different; all the audience needs to pay attention to is the body language of the actors. If the worldwide audience starts to learn Chinese due to their love for martial arts films, then they would not only watch martial arts films in the future, but might also appreciate Chinese dramas. In the future it would not only be Chinese martial arts films being appreciated internationally, but also artistic films and even television shows.
            </p><p>After the forum I returned to the hotel. Whenever I have completed all my work I feel really happy to be back at the hotel so I can just comfortably lie in bed and watch Discovery!
            </p>
          </section>
          <section>
            <h2>Jackie Chan Shanghai Racing Charity Weekend</h2>
            <p>The next day, the first job I had was to meet with Huang Yi, one of the leading actresses of the television series Everlasting Regret, and Mr. Yu Zhi Fei, a representative of Shanghai Grand Prix, and to attend the press conference for the 2005 Jackie Chan Charity Cup which is scheduled to take place in Shanghai this year. At the conference, I told the media that the guests who are scheduled to attend so far include Sammi Cheng (popular artist in Southeast Asia, rumored to be extremely ill), Joey Yung (no need for introductions; she attended the Jackie Chan Cup last year), Nicholas Tse (who was in New Police Story ), Jolin Tsai (very popular Chinese artist), Kim Hee (Korean leading actress of The Myth ), Yumiko Cheng, Fan Bing Bing, Big S Barbie Xu, Small S Xu Xi Di, Angelica Lee, Huang Yi and Kelly Lin. My apologies for not being able to introduce every single artist, but they are all very popular artists in Asia. They are giving up their valuable time for charity, so I am very grateful for their support.
            </p><p>The 2005 Jackie Chan Charity Cup will take place on September 4, and this year's event time will be extended from the usual one day to about a week. It is tentatively titled Jackie Chan Shanghai Racing Charity Weekend. Why this particular name? At the moment I plan to have a charity concert on September 2, and September 3 would be a charity ball. Therefore, apart from the celebrity race, there would also be a notable people's cup competition. Every year approximately 20 ¡V 30 celebrities take part in the charity race, but it seems like it is a waste for them to attend only one event. I thought it might be a good idea to have one or two races, or another form of event, and hopefully raise more funds for the Jackie Chan Charitable Foundation. It could also help raise funds for the Children's Foundation and the Shanghai Charitable Foundation. With that, it would further assist more charity organizations. I hope that this Jackie Chan Shanghai Racing Charity Weekend could raise 7 or 8 million dollars, and I am very happy to say that up until now, there have been many charitable people who have promised to donate to the event, with the amount reaching $6 million. We are only approximately $2 million away from the target and we will work hard to ensure we reach it!
            </p>
          </section>
          <section>
            <h2>Everlasting Regret Press Conference</h2>
            <p>After the press conference, I immediately returned to the hotel to get changed and prepare myself for the next job. What kind of a job is it? Another press conference! I have to attend the press conference for my financed television show, Everlasting Regret . If you have a good memory, you probably recall that I had already attended a press conference for Everlasting Regret . That one was for the film version and this time it is the television version. I was there with the leading cast Huang Ye, Maggie Cheung Ho Yee and Tse Kwan Ho, arriving on a jinricksha with tunes of Night Shanghai playing in the background.
            </p><p>At the press conference, many journalists asked me why I would invest in the film and television version of Everlasting Regret . As a person who works in the entertainment industry, I not only have a record production company in Beijing with Jonathan Lee Tsung Sheng, but also my own film production company. I've not only invested in action films in the past, but films like Centre Stage and Rouge , in hopes of producing a wide range of films. This time I invested in the two versions of Everlasting Regret, with both versions having different cast members and directors. Also, a journalist asked me why I asked a Beijing director to direct a Shanghai story. I told them that I don't think of him as a Beijing person; you're Taiwanese, I'm from Hong Kong - we're all human beings living in this world. Everyone at the event tonight is Chinese and no matter who we are, we should be working together to come up with the best way to make a good film, so we can promote it to the world. This to me is the most important thing!
            </p><p>After the press conference, we all went to the top floor of a building at The Bund for some food. We sat near the windows, and looking out from the restaurant, the scenery was so breathtakingly beautiful; the whole Huangbu River presented in front of our eyes. I don't know whether you're aware that there are many top floor restaurants at The Bund now. The next time you visit you should try and go to one of those. Not only would you enjoy the delicious food, but also the gorgeous views. After the meal, we all returned to the hotel to rest, because next morning we had to rush back to Hong Kong.
            </p><p>This morning I took a flight back to Hong Kong and by the time I got back it was already noon. It's summer in Hong Kong at the moment and summer means rainy season's here, so heavy rain is a common sight now. Rain is a valuable thing to many people and things. For example, we receive sufficient water so Hong Kong does not need water restrictions. The trees get enough water and blossom. However, to me it proved to be more harm than good. Why? Because after the heavy rain, my Kowloon Tong office began to show signs of water leaking, so after I got off the plane I immediately rushed back to check where water is leaking in. I even dragged a repairman to point out the leakages one by one, and requested that he immediately fix the problem.
            </p><p>After arranging the repair job, I had a scrīpt meeting. With my new film busily being in preparation- it will begin production in August - I will have scrīpt meetings whenever I have time to ensure that the scrīpt is as good as it can be.
            </p><p>That's all for now, until next time, good-bye!</p>
          </section>
        </article>
        <article> 
          <section>
            <h2>遺忘了的事情：</h2>
            <p>我剛從上海回到香港，這幾天可以說是馬不停蹄，我回想臨出發到上海之前的兩天，都是非常忙碌，既要錄音，又要探訪老人院，所以忘記了告訴大家一件事。在六月九日，金喜善到了香港，她這次來的目的是和我一起錄兩首歌曲。其實，這兩首歌是為今年九月的慈善演唱會而唱的，因為我和她都沒有空，幾經安排方抽到這段時間，我們兩人可以走在一起錄這兩首歌。金喜善和經理人抵港後，我當然盡地主之誼請他們吃飯，其後一起到卡拉 OK 練歌，不久就送他們回酒店休息。
            </p><p>翌日，金喜善走進錄音室錄歌時，她的表現令監製大表詫異，她唱了“明明白白我的心”和“在我生命中的每一天”，她的國語咬字非常標準，可想自我送了這兩首歌的光碟給她後，她下了多少苦工。我想告訴大家，金喜善是不懂看中文的，所以她是牢記每個字的發音，還要記著旋律，但是最諷刺的就是當她牢牢記著所有發音，跟著旋律唱完歌，我反而忘記歌詞和跟不上拍子，真是丟臉！
            </p><p>完成兩首歌的錄音後，我方知明天是金喜善的生日，她會明天趕回韓國，於是我和楊生（我的好朋友兼生意拍檔楊受成）為金喜善舉辦了一個神秘生日會。因為時間倉促，不算是什麼神秘生日會，只是約了些同事和朋友到卡拉 OK 而已。坦白說，當晚我不是太開心，看著他們盡飲盡唱，而我腦裡想著很多事情，想著將要到上海做的事情，還有些生意上的事煩著，所以一邊想著，一邊聽著在場的女仔在叫囂暢飲，我也開始有些煩躁了。於是，我叫公司的女同事先走，不久生日會也曲終人散。
            </p>
          </section><section>
            <h2>上海國際電影節：</h2>
            <p>六月十一日，金喜善一行人回韓國，而我有我的工作，早上直飛到上海，出席第八屆的上海的電影節。電影節在上海大劇院拉開帷幕，為了營造華語電影百年慶的氣氛，此次電影節組委會特意將紅地毯延長，重金包機，邀請北京 300 位明星前往上海。當我到達會場時，看到熱情的影迷不斷歡呼和揮手，人山人海的影迷也把整晚的氛圍烘托到了極點。
            </p><p>我參與電影節時，方知道大會頒發特別獎項給我和張藝謀導演，就是‘華語電影傑出貢獻獎'。坦白說，當我上台時，我感到很詫異，竟然頒發這個獎給我；本來我只是出席是次電影節作嘉賓，並且參加論壇而已，真想不到會有此驚喜。
            </p><p>在台上，我向大家說，第一、我不敢說有什麼貢獻，如果說有貢獻的話，我要多謝前人和前輩，幫我們一步一步的走下來，我希望學前輩一樣，可以在他們的步法前或後多留下足跡，令後輩所走的路得更平坦，更易走，跳得更遠。第二、可以跟張藝謀導演一同得到這個獎項，我感到這是一個榮耀。
            </p><p>告訴大家一件事，這個傑出貢獻獎獎杯非常重，是楊慧珊的琉璃工場所造的，不是說笑，真的很重很重，我要為如何處置它而大傷腦筋。如果放在箱中運回香港，恐防運送途中損毀；如果手提上機又太重，最後我決定交到我在上海的傢俬工場，下次運送貨品時，跟隨貨櫃運回香港比較安全了。
            </p>
          </section><section>
            <h2>第八屆上海國際電影節高峰論壇：</h2>
            <p>翌日，我出席一個論壇，是第八屆上海國際電影節高峰論壇，內容談及如何把功夫片更加發揚光大？他們名命為‘中國功夫電影對世界的影響'。我真的想不到，只是一個小小電影論壇，竟然會造成一次小混亂，是緣是次論壇吸引了眾多專家和媒體關注，當我出現時，現場幾度混亂，而記者在電梯內滯留了數分鐘才得以脫身，這真是我始料不及。
            </p><p>坦白說，當我上台時，掌聲如雷，經歷大場面無數的我也有些緊張，我緊張是因為中國功夫對世界影響話題太大，不知道我能否表達準確，我也不知道從何說起，但如果要評價功夫片我應該最有資格。因為，我打從六歲半就開始拍攝功夫電影，那時所謂的舊功夫時代借助“黃飛鴻”系列片展示中國的武術，這叫做‘掌風功夫電影'，演員表演時打得很慢，四個人在打架，後面兩個人在等；到了王羽的時代，功夫片發展成為主演一轉身，四五十個壞人便會全都死掉；再到李小龍的時代，才有了功夫片應有的震撼力。那個時候受李小龍影片的影響，我重回武館去學功夫，於是開始了成龍時代。
            </p><p>談到關於我對功夫片的最大貢獻，我想就是讓功夫幽默化，讓人看完功夫片感到開心。後來，我發覺自己的影片可以打入世界，讓中國的功夫片得到全世界觀眾的喜愛。目前，我在英國、澳洲、加拿大、非洲、韓國、日本擁躉無數，而且全世界都有我的影迷會。他們看過我的功夫片后開始學習漢語，來中國學功夫，來到香港看我，還有很多聽我說國語，很多德國人都會唱《明明白白我的心》，這就是我對他們的影響。就好像最近興起的‘韓流'，有很多深受觀眾歡迎的韓國影片引進到中國並開始影響觀眾，以至於現在很多中國人開韓國餐廳，去韓國玩，我知道很多朋友在學韓語。
            </p><p>在我看來，只要電影拍得好，又可以讓世界觀眾接受，‘這就是我對他們的影響'！因為香港功夫片的成功，使得功夫片成為了一個電影類型，其中功不可沒的就是張藝謀和李安導演，他們把傳統的功夫片昇華了，畫面更漂亮，他們的作品可以媲美荷里活的電影。
            </p><p>我在荷里活叱吒多年，對中國功夫片在海外的受眾有著深刻了解，我認為，把中國演員和中國傳統文化推向世界觀眾，功夫片無疑是最好的載體。我希望以后有更多的外國人學習漢語，並對我們的傳統文化產生興趣。我有兩個澳洲徒弟來到北京學漢語，受到我的影響，他們現在也開始穿唐裝，我對他們說，要向我學藝就先做一個中國人。我希望中國所有的電影人在任何一個場合都要把自己的中國文化帶出去，這樣可以令更多的外國人喜歡中國的文化，這樣他們就會開始學漢語，了解中國文化。
            </p><p>我又認為，功夫片的最大優勢在於簡單易懂，不太受語言限制，你們看張藝謀的“大紅燈籠高高掛”，導演要花心思去想台詞‘到哪個姨太太房間去'，但再精彩的對白，英語翻譯都可能只是一個 YES ，或一個 NO ，很難讓外國觀眾真正了解影片的內涵。動作片就不用了，只用看演員的肢體語言就可以了。如果全世界觀眾由於喜歡功夫片而學習漢語，他們以後就會不單看功夫片，還可以看更多的中國文藝片。以後不僅是中國功夫片走向全世界，文藝片和電視劇都可以走向全世界。
            </p><p>論壇完畢後，我回到酒店，每天把工作完成後，回到酒店都感覺到很開心，我可以隨心所欲的躺在床上看 Discovery 。
            </p>
          </section><section>
            <h2>《成龍上賽慈善週末》：</h2>
            <p>第二天早上，第一個工作就是與電視劇“長恨歌”的女主角之一的黃奕和上海賽車場（上賽）的郁知非（郁總）一起出席在上海舉行的《 2005 年成龍慈善盃》記者會。記者會上，我透露已答應屆時出席的嘉賓包括被傳患重病的鄭秀文（東南亞的當紅女藝人，曾在我的合唱專集中與我合唱一曲）、容祖兒（不用我多介紹，去年也有出席成龍盃）、謝霆鋒（曾參與“新警察故事”）、蔡依林（紅遍中港台的女藝人）、金喜善（“神話”的韓國女主角）、鄭希怡、范冰冰、「大 S 」徐熙媛、「小 S 」徐熙娣、李心潔、黃奕和林熙蕾等等，恕我未能一一向大家介紹每一位藝人，但他們全都是亞洲的當紅男女藝人，今次為了做善事而抽出時間參與，我非常感謝他們。
            </p><p>《 2005 年成龍慈善盃》於九月四日舉行，將延長舉辦時間，由以前的一日增至約一星期，暫名為《成龍上賽慈善週末》。為何有這個名字呢？因為我打算在九月二日舉行慈善演唱會、九月三日舉辦慈善晚會，所以除原本的明星賽外，還會增設名人盃賽。每一年舉辦成龍慈善盃都有二、三十位藝人參與，只出席一個活動似乎很浪費，我想倒不如多設計一至兩場賽事，或是不同形式的活動，希望為成龍慈善基金籌得更多善款，幫助‘兒基會'和捐助上海慈善基金會，從而幫助其他有需要的慈善團體。我希望這一次《成龍上賽慈善週末》可以籌得七百至八百萬的善款，好高興截至現在為止，已經有不少善長人翁答應捐出善款，合共有六百萬，距離目標只差百多二百萬，我們會繼續努力！
            </p>
          </section><section>
            <h2>“長恨歌”記者招待會：</h2>
            <p>完成了這個記者會後，我立即趕回酒店，換過衣服，準備下一個工作了。是什麼工作？又是記者會，我出席由我參與投資的電視劇“長恨歌”記者會。如果大家心水清的話，可能會記得早前我已經出席過“長恨歌”的記者會，那次是電影版的記者會，而今次是電視版，我和劇中男女主角黃奕、張可頤、謝君豪坐著黃包車在“夜上海”的唱機歌聲中亮相。
            </p><p>記者會上，有很多記者問為什麼我會投資“長恨歌”的電影和電視？我身為一個從事娛樂事業的人，不但跟李宗盛在北京開唱片製作公司，還有自己的電影公司；而且，我不單單投資動作電影，還 投資拍過“阮玲玉”和“胭脂扣”等電影，為的就是希望有多元化的製作。今次投資“長恨歌”電影和電視版本，兩個版本的導演和演員都是不同的。這時，又有記者問我為什麼請一位北京的導演拍一部上海戲？我向他們說，現在不要再分他是北京人、你是台灣人，我是香港人，我們全都是地球人，今晚在座各位都是中國人，無論是什麼人，大家都應該通力合作，想辦法拍好電影，把它推廣到全世界，這才是這重要的！
            </p><p>記者會後，我們大伙兒到上海灘頭的一所大廈的頂樓吃東西，我們坐到一個靠窗的位置，從餐廳向外望，景色真的很美很美，整個黃埔江盡入眼簾。不知大家知不知道，現在的上海灘有很多這樣的頂樓餐廳，大家下次到訪上海，不妨挑其中一間試試，不但可以享受美食，更可以大飽眼福。用餐後，大家立即回酒店休息，因為明早又要趕回香港了。
            </p><p>今早，乘早機回香港，回到香港已經是中午。現時正值香港的夏季，夏季是香港的雨季，不時會大雨連場，下雨對很多人或物都是好事，例如有足夠的水，香港不用制水；樹木有足夠的水，可以開得更茂盛。可是，對我而言就苦不堪言了，為什麼？因為九龍塘公司在大雨後，竟有漏水的現象，所以甫下機，我馬上趕回九龍塘公司，檢查公司那處有漏水，我還拉著建築師，把漏水的地方一一指出，要求他盡快修補漏水的地方。
            </p><p>安排了修補工作後，我投入開劇本會。新戲現正密鑼緊鼓籌備中，八月會開鏡，所以現在我有空就開劇本會，希望把劇本弄得盡善盡美。
            </p><p>就此擱筆，下次再談吧，拜拜。</p>
          </section>
        </article>
      </div>
    </section>
  )
}